language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: "N0sbxLsN0OVaGImgUeqB3n/xb5Tla2sbD4rGrqP2cauG9sHqP5YmSAB2cUisoke677XUnCnIKZcOVi8fMk1bxtVXwX3JMsrbFZAD8kW9KpBCS8oQqxc/X7Yc+rj3iFAUH+5mhGS/VFZFlYjJuaoshcajlob/UKtutop5I8XTWFr1sBiRNBPlL9GMuy7PLxXma8Yoo7eQ7SHtZOHAcLpWYWYbkeXP1150DET1iM7EdvQDERWtbjdJblzlEJXmiQL+YDZDx+oiysgGPVP0LbRrcIWeZAt00XHtJvJvhpkVOjeiCD8Atnzjt+X3NNDKkk2ll7hhaJ+VlnbnT5Jn2tqk/HMNBdF39fa2SoULzreJzrvp35JLhO20enJFHecf9L2OX8Q51S/yDU+KXNyQmF5OqHolE4pnJAzmtmv8els9137QUHo9pezx0jfF6+RFi9Tdy4u7YMCH8n3AmzzYUJETjAzLYXmuoyEwLQvP3c/Ttuq1K1k6uj1g50m4PDnmVL517WmndyxalIABC4vSYFu5ZcZLhHawx3wp76EuvNwoozrrUkZO+Ytz5L0eYYlnTZhCIvCl2wLs//B9oLXdVOCe89nm1mRT3fmoT48PzDLElqjZEhL/Ibi3+ruK/AveAfC5KRG0O6/1EgRuf2c8K2FCh36gUyfGOlacsdeiDJW51dw="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "rVH2W3qLfcH1cUDTE2buzSJDHJ6TEwFsIPli11o2UBut9477gnU0sB7zhcSkM10yqBntU6o3uVy5YXbHudbc5Ivj2aAQBMX09v+TpxFymIlKj6g+xVelDHrIRxky747lzSq/Ghze83dXDiE58hmrYyZ0cPvIg4pJA7VoJILc5VMZhbut9zIW/2l/b8W8ugqaATDthoXHaozZkWBCetpnZg9nGJ3H2W8l3UUaXc+f1aG9SldiECyX9aX7JiJwZCF3Lvn8SHwM5QggrfE64QNvyT5YHTkTsOURXsPUsEYtCDk1sbGSKf64pgdsPrBeonGWfRjBkDoQi0o1o0bUBFgspemjolfI4zjgWqho3ezzE9V2nskAaLwaeThY+AeMfKMrccnQ4S4hf0l6GRaNPPYOzUQ+1iMEojnRbPKRzGmWlZ7Lx+NdLbT6gcvor1bqb3PwyMMnZgeoeilJHAxn3EpYlxqtj8g56q4iySOc6XR/BosvM1islgzRHbtbRigvU+KUzAAhPWAqx17RHEcjlbyntXSaE0KmPlYzX7e56pHBIwVgzAj8LrxkjJco8AiDKN8mZzYgvzB7oUYyQMT3a1lQdNot49MiSpMSFq4fy2qhi+Tkjx0vQYfC68+/coXxvh49GJY+Be9657yOVPx8n640Ai0+X8Zs5wu5DurJjgq2EYc="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "SM7g8xieth1Ac8cxD24EnlFDPIEfMY3dodSN9GIwqHQ3SWrsaiv6Fs0MnV5ghBrp+2/rBcLMkHEHQ9T3vlzMFDLNPzWxoRpSZu5ZJkf67YCbPTJfpirRcL5Ajz2EVn1Z9Z/70NJKOb2RBW7RlLdmINcwImxyvctjrbT5I15zxY8Lr3kNZsLoPAUqLqzGkkA8cpfMnUUWNsdG5BiJxlQirFyolcpVdyRjV8mb6BEeKCRKydntvqmWdQiHp8XPnCvmkqlV9JrVa5qNRiBCSv8Xu/5pej7oStk2EJe9+dIQFO4cO0HZ3M5DcjBv8nVw828hWjCaPWxKCyqrb6YtPMhnO6ZKDp4vI8BrdokoDzBF29Psyce/w6YUtKO0GdBzcXth8pTpoiX457RbqK4BJcUw67btd4UqzcxVxWB0QOxb8dp0GpHcNU4yzyxC2XC4ruuzShmI+d5tWzJYLOATyFJ0tbqqYGzFcjLf3Ph6Z+c1PCtTahn09EV0EQ9NdNWryAq2gIAl530/T6f4FyWvRSbjEK5yzrlBACg7gpdTlIpulbvtT5yyeTdLtZKloOWoaUc0PHrG9vG6iRQVLRIFPXMPWgf7HxQDp5yIhUECrKy7NvoMgwZ8Bwv+Qu62qfOelJ0lX+LT5HdBsYmpuW5gaqxKUA7aXJxoASvqgdazApFapMY="
    - # ^^ GPG_KEY_NAME
    - secure: "H4ynJXZsNjlvx3qo4LnTxR6HIuvrERX2yeEIAPudOpPzPqcAlsPT89K9lGPnGaItpJvflTkly/ITpLpSnbkZRVez+M8l2EFmgpsQA+/zSXDEO1UXyfojsMGWC/Hbx4FscoTJjI/gD2HcxfAy8+VrBmjzLifahO7puBz0HIG80lz/62kDU+0T+JZ8gTsu2gd6diEq/UZnTedCuysstthIlV8Lo0eaLsEb9JUiTpNbifcmNejyKCsPBHYnM/lmV7h0ogC4flbRUR9pIy8KEEPODVJb5R77eXMzIymJWa3waWmAk1CPw105KZlg4ioXC4xjV6pG7pxnZxoQTS7+eMGI18Jtd8sXNInJ79x/tDjPFFmBpQCuEbQHl4Gx6oF868CFz5P2L1d5Uysv6U5ek5dRG0wEjMoDfCAtXPUsoYaedo/IK9x6ZRaQ/51+NPpIENZpHjGVe4m78ROWK+/ia5unYKYoUViwa7zOyk2homgL9+47Cgz2ddP2JviZ28Q4tOZk3pbzEGwf9l8WCST9utQn8wqvFMO4H/5QwPTcNf/LB/0PyurnAcKz0ChPfSlH7/alGLmImAxk7WMbMyoYBImlllXBmq7e7CzH+FioFIh4beLlSRnQ7Okh4BY0eE9HhhP4qd1ug+HdiOnFVaI9HjGpeMMXEpY88oUPP+mPR6SPlFU="    - # ^^ GPG_PASSPHRASE

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P deploy
